import type { Metadata } from "next";
import { Inter, Lugrasimo } from "next/font/google";
import "./globals.css";
import TanstackQueryProvider from "@/providers/tanstackQueryProvider";
import Navbar from "@/components/navbar";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanstackQueryProvider>
       <body className={inter.className }>
        <Navbar />
        <Toaster />
        {children}
        </body>
      </TanstackQueryProvider>
    </html>
  );
}
